name: "Check branch rules"

on:
  pull_request:

jobs:
  check-changesets:
    name: Check if changeset release
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.is-changeset-release.conclusion }}
    steps:
      - name: Skip on changeset releases
        if: ${{ startsWith( github.head_ref, 'changeset-release' ) }}
        id: is-changeset-release
        run: exit 1
        continue-on-error: true

  check_branch:
    name: Check branch rules
    runs-on: ubuntu-latest
    needs: check-changesets
    if: needs.check-changesets.outputs.status == 'success'
    steps:
      - name: Throw error if wrong branch
        if: github.base_ref == 'main' && github.head_ref != 'pre-release'
        run: |
          echo "ERROR: You can only merge to main from pre-release."
          exit 1
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
      - run: npm ci
      - name: Ensure pre-release branch is in pre-release mode
        if: github.base_ref == 'pre-release' && startsWith('release/', github.head_ref)
        run: |
          ! npx changeset pre enter beta &>/dev/null || (echo "Pre-release branch must be in pre-release mode, please run \`npx changeset pre enter beta\` and commit the changes" && exit 1)
      - name: Ensure main branch is not in pre-release mode
        if: github.base_ref == 'main'
        run: |
          npx changeset pre enter beta &>/dev/null || (echo "Main branch must not be in pre-release mode, please run \`npx changeset pre exit\` and commit the changes" && exit 1)
