name: "Check Branch"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Throw error if wrong branch
        if: github.base_ref == 'main' && github.head_ref != 'pre-release'
        run: |
          echo "ERROR: You can only merge to main from pre-release."
          exit 1
      - name: Ensure pre-release branch is in pre-release mode
        if: github.base_ref == 'pre-release'
        run: npx changeset pre enter beta
