name: "Check Branch"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Throw error if wrong branch
        if: github.base_ref == 'main' && github.head_ref != 'pre-release'
        run: |
          echo "ERROR: You can only merge to main from pre-release."
          exit 1
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
      - name: Ensure pre-release branch is in pre-release mode
        if: github.base_ref == 'pre-release'
        run: ! npx changeset pre enter beta || echo "Pre-release branch must be in pre-release mode, please run `npx changeset pre enter beta` and commit the changes"
