name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - pre-release
    types:
      - closed

env:
  HUSKY: 0

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for changesets
  pull-requests: write # Required for changesets

jobs:
  release:
    if: github.event.base_ref == 'main' || github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          check-latest: true
          cache: npm

      # Ensure npm 11.5.1 or later is installed for OIDC
      - name: Update npm
        run: npm install -g npm@latest

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/work/packages/packages/node_modules/.cache/eslint/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/.eslintrc.cjs') }}

      - name: Install Dependencies
        run: npm ci

      - name: Check pre-release is in beta mode
        if: github.event.base_ref == 'pre-release'
        run: |
          ! npx changeset pre enter beta &>/dev/null || (echo "Pre-release branch must be in pre-release mode to run a release, please run \`npx changeset pre enter beta\` and commit the changes" && exit 1)

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run release
          setupGitUser: true
