name: Test potential merges
on:
  pull_request:
    branches: [main, pre-release]
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Skip on changeset releases
        if: ${{ startsWith( github.action_repository, 'changeset-release' ) }}
        id: is-changeset-release
        run: exit 1
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/work/packages/packages/node_modules/.cache/eslint/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/.eslintrc.cjs') }}
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - name: Is changeset release
        if: ${{ failure() && steps.is-changeset-release.conclusion == 'failure' }}
        run: exit 0
